In [2]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

df = pd.read_excel("All_Villagesof_India_2026-04-10_16-24-30.xlsx", skiprows=1)

print(df.head())

   S.No.  State Code      State Name (In English)  District Code  \
0      1          35  Andaman And Nicobar Islands            603
1      2          35  Andaman And Nicobar Islands            603
2      3          35  Andaman And Nicobar Islands            603
3      4          35  Andaman And Nicobar Islands            603
4      5          35  Andaman And Nicobar Islands            603

  District Name (In English)  Sub-District Code  \
0                   Nicobars               5916
1                   Nicobars               5916
2                   Nicobars               5916
3                   Nicobars               5916
4                   Nicobars               5916

  Sub-District Name (In English)  Village Code  Village Version  \
0                    Car Nicobar        645012                1
1                    Car Nicobar        645013                1
2                    Car Nicobar        645016                1
3                    Car Nicobar        645017                1
4                    Car Nicobar        645020                1

  Village Name (In English) Village Name (In Local) Village Category  \
0                       Mus                     NaN            Rural
1                    Teetop                     NaN            Rural
2                    Kimois                     NaN            Rural
3                    Kakana                     NaN            Rural
4                     Perka                     NaN            Rural

  Village Status  Census 2001 Code  Census 2011 Code
0     Inhabitant             35700            645012
1     Inhabitant             35800            645013
2     Inhabitant             36100            645016
3     Inhabitant             36200            645017
4     Inhabitant             36500            645020

In [4]:
print("Columns in dataset:\n")
for col in df.columns:
    print(col)

Columns in dataset:

S.No.
State Code
State Name (In English)
District Code
District Name (In English)
Sub-District Code
Sub-District Name (In English)
Village Code
Village Version
Village Name (In English)
Village Name (In Local)
Village Category
Village Status
Census 2001 Code
Census 2011 Code

In [5]:
# Clean column names
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("(", "", regex=False)
df.columns = df.columns.str.replace(")", "", regex=False)

print("Cleaned Columns:\n")
print(df.columns)

Cleaned Columns:

Index(['S.No.', 'State_Code', 'State_Name_In_English', 'District_Code',
       'District_Name_In_English', 'Sub-District_Code',
       'Sub-District_Name_In_English', 'Village_Code', 'Village_Version',
       'Village_Name_In_English', 'Village_Name_In_Local', 'Village_Category',
       'Village_Status', 'Census_2001_Code', 'Census_2011_Code'],
      dtype='object')

In [6]:
df.rename(columns={
    'State_Name_In_English': 'state',
    'District_Name_In_English': 'district',
    'Subdistrict_Name_In_English': 'subdistrict',
    'Village_Name_In_English': 'village',
    'Village_Code': 'village_code'
}, inplace=True)

print("Columns renamed ✅")

Columns renamed ✅

In [7]:
df = df[df['state'] == 'Punjab']

print("Filtered Punjab Data ✅")
print("Remaining rows:", len(df))

Filtered Punjab Data ✅
Remaining rows: 13014

In [8]:
districts = ['Bathinda', 'Rupnagar', 'Fatehgarh Sahib']

df = df[df['district'].isin(districts)]

print("Filtered Selected Districts ✅")
print("Remaining rows:", len(df))

Filtered Selected Districts ✅
Remaining rows: 1382

In [9]:
df = df.drop_duplicates()
df = df.dropna(subset=['village', 'village_code'])

df.reset_index(drop=True, inplace=True)

print("Cleaned Data ✅")

Cleaned Data ✅

In [10]:
# Select correct columns
final_df = df[['state', 'district', 'Sub-District_Name_In_English', 'village', 'village_code']]

# Rename for consistency
final_df.rename(columns={
    'Sub-District_Name_In_English': 'subdistrict'
}, inplace=True)

print("Final Data Preview:")
final_df.head()

Final Data Preview:

    state  district subdistrict             village  village_code
0  Punjab  Bathinda    Bathinda     Aklia Kalan (8)         35759
1  Punjab  Bathinda    Bathinda     Aklia Khurd (7)         35760
2  Punjab  Bathinda    Bathinda  Blahar Mehma (171)         35761
3  Punjab  Bathinda    Bathinda  Blahar Vinju (166)         35752
4  Punjab  Bathinda    Bathinda        Bhokra (160)         35741

In [11]:
print(df.columns.tolist())

['S.No.', 'State_Code', 'state', 'District_Code', 'district', 'Sub-District_Code', 'Sub-District_Name_In_English', 'village_code', 'Village_Version', 'village', 'Village_Name_In_Local', 'Village_Category', 'Village_Status', 'Census_2001_Code', 'Census_2011_Code']

In [12]:
final_df.to_csv("cleaned_punjab_villages.csv", index=False)

print("🎉 File saved successfully!")

🎉 File saved successfully!

In [13]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# Load GP mapping file
gp_df = pd.read_excel("Village_Gram_Panchayat_Mapping_2026-04-10_16-53-28.xlsx", skiprows=1)

print("GP File Loaded ✅")
print(gp_df.columns)
gp_df.head()

GP File Loaded ✅
Index(['S.No.', 'District Code', 'District Name (In English)',
       'District Census 2011 Code', 'District Census 2001 Code',
       'Subdistrict Code', 'Subdistrict Name (In English)',
       'Subdistrict Census 2011 Code', 'Subdistrict Census 2001 Code',
       'Village Code', 'Village Name (In English)', 'Village Census 2011 Code',
       'Village Census 2001 Code', 'Local Body Code',
       'Local Body Name (In English)'],
      dtype='object')

,S.No.,District Code,District Name (In English),District Census 2011 Code,District Census 2001 Code,Subdistrict Code,Subdistrict Name (In English),Subdistrict Census 2011 Code,Subdistrict Census 2001 Code,Village Code,Village Name (In English),Village Census 2011 Code,Village Census 2001 Code,Local Body Code,Local Body Name (In English)
0,1,27,Amritsar,49,2,255,Ajnala,255,1,37270,Abu Said (250),37270,180600,237914,Abu Said
1,2,27,Amritsar,49,2,255,Ajnala,255,1,37252,Aliwal (117),37252,178800,237915,Aliwal
2,3,27,Amritsar,49,2,255,Ajnala,255,1,37253,Anayatpura (118),37253,178900,237947,Anaitpura
3,4,27,Amritsar,49,2,255,Ajnala,255,1,37122,Arazi Darya (52),37122,165800,237951,Galib
4,5,27,Amritsar,49,2,255,Ajnala,255,1,37083,Arazi Kassowala (77),37083,161900,237953,Ghoney Wahala

In [14]:
# Clean column names
gp_df.columns = gp_df.columns.str.strip()
gp_df.columns = gp_df.columns.str.replace(" ", "_")
gp_df.columns = gp_df.columns.str.replace("(", "", regex=False)
gp_df.columns = gp_df.columns.str.replace(")", "", regex=False)

print("Cleaned Columns:")
print(gp_df.columns)

Cleaned Columns:
Index(['S.No.', 'District_Code', 'District_Name_In_English',
       'District_Census_2011_Code', 'District_Census_2001_Code',
       'Subdistrict_Code', 'Subdistrict_Name_In_English',
       'Subdistrict_Census_2011_Code', 'Subdistrict_Census_2001_Code',
       'Village_Code', 'Village_Name_In_English', 'Village_Census_2011_Code',
       'Village_Census_2001_Code', 'Local_Body_Code',
       'Local_Body_Name_In_English'],
      dtype='object')

In [15]:
gp_df = gp_df[[
    'Village_Code',
    'Village_Name_In_English',
    'Local_Body_Name_In_English',
    'Subdistrict_Name_In_English',
    'District_Name_In_English'
]]

# Rename columns
gp_df.rename(columns={
    'Village_Code': 'village_code',
    'Village_Name_In_English': 'village',
    'Local_Body_Name_In_English': 'gp_name',
    'Subdistrict_Name_In_English': 'block',
    'District_Name_In_English': 'district'
}, inplace=True)

print("GP Data Selected & Renamed ✅")
gp_df.head()

GP Data Selected & Renamed ✅

   village_code               village        gp_name   block  district
0         37270        Abu Said (250)       Abu Said  Ajnala  Amritsar
1         37252          Aliwal (117)         Aliwal  Ajnala  Amritsar
2         37253      Anayatpura (118)      Anaitpura  Ajnala  Amritsar
3         37122      Arazi Darya (52)          Galib  Ajnala  Amritsar
4         37083  Arazi Kassowala (77)  Ghoney Wahala  Ajnala  Amritsar

In [16]:
# Remove duplicates
gp_df = gp_df.drop_duplicates()

# Remove null values
gp_df = gp_df.dropna(subset=['village_code'])

# Convert to string (VERY IMPORTANT for merge)
gp_df['village_code'] = gp_df['village_code'].astype(str)

print("GP Data Cleaned ✅")

GP Data Cleaned ✅

In [17]:
# Convert village_code to string
final_df['village_code'] = final_df['village_code'].astype(str)

print("LGD Data Ready ✅")

LGD Data Ready ✅

In [18]:
merged_df = pd.merge(
    final_df,
    gp_df,
    on='village_code',
    how='left'
)

print("🎉 Merge Successful!")
merged_df.head()

🎉 Merge Successful!

,state,district_x,subdistrict,village_x,village_code,village_y,gp_name,block,district_y
0,Punjab,Bathinda,Bathinda,Aklia Kalan (8),35759,Aklia Kalan (8),Akalian Kalan,Bathinda,Bathinda
1,Punjab,Bathinda,Bathinda,Aklia Khurd (7),35760,Aklia Khurd (7),Aklia Khurd,Bathinda,Bathinda
2,Punjab,Bathinda,Bathinda,Blahar Mehma (171),35761,Blahar Mehma (171),Balahar Mehma,Bathinda,Bathinda
3,Punjab,Bathinda,Bathinda,Blahar Vinju (166),35752,Blahar Vinju (166),Balahar Binjhu,Bathinda,Bathinda
4,Punjab,Bathinda,Bathinda,Bhokra (160),35741,Bhokra (160),Bhokhra,Bathinda,Bathinda

In [19]:
merged_df = merged_df[[
    'state',
    'district_x',   # from LGD
    'subdistrict',
    'block',
    'gp_name',
    'village_x',
    'village_code'
]]

# Rename columns properly
merged_df.rename(columns={
    'district_x': 'district',
    'village_x': 'village'
}, inplace=True)

print("Final Dataset Ready 🚀")
merged_df.head()

Final Dataset Ready 🚀

,state,district,subdistrict,block,gp_name,village,village_code
0,Punjab,Bathinda,Bathinda,Bathinda,Akalian Kalan,Aklia Kalan (8),35759
1,Punjab,Bathinda,Bathinda,Bathinda,Aklia Khurd,Aklia Khurd (7),35760
2,Punjab,Bathinda,Bathinda,Bathinda,Balahar Mehma,Blahar Mehma (171),35761
3,Punjab,Bathinda,Bathinda,Bathinda,Balahar Binjhu,Blahar Vinju (166),35752
4,Punjab,Bathinda,Bathinda,Bathinda,Bhokhra,Bhokra (160),35741

In [20]:
merged_df.to_csv("final_village_dataset.csv", index=False)

print("🎯 FINAL FILE SAVED SUCCESSFULLY!")

🎯 FINAL FILE SAVED SUCCESSFULLY!